### ISSUE TITLE
Naming conventions for output files/folders

### ISSUE THREAD

**Issue by bpaniagua** [laurapascal/SPHARM-PDM#1]
@laurapascal:

The output folder should organize outputs from the three different functional units of spharm-pdm in a self-explanatory way. I apologize for not specifying this earlier.
Changes needed:

PostProcess --> Step1_SegPostProcess
MeshParameters --> Step2_GenParaMesh
SPHARMMesh --> Step3_ParaToSPHARMMesh

The output files in the SPHARMMesh (to be Step3_ParaToSPHARMMesh) should be as follow:

OriginalFilename_pp_surf_[filenames of ParaToSPHARMMesh]
(this indicates that postprocess "pp" has been ran, as well as genparamesh "surf")

Right now is 

OriginalFilename[filenames of ParaToSPHARMMesh]

**Comment by laurapascal** [comment]
Fixed with these two commits: 
- Modification of the output folder names: [be4aeea](https://github.com/laurapascal/SPHARM-PDM/commit/be4aeea9e3c1f889d0813e56db8bc72798e8729b) 
- Modification of the ParaToSPHARMMesh output file names:  [2565bcd](https://github.com/laurapascal/SPHARM-PDM/commit/2565bcd50fd2d6521deb8ce821373aad760df758)
